# Generated by Django 2.0.7 on 2018-10-11 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='轮播图标题')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='轮播图片')),
                ('url', models.URLField(verbose_name='轮播图访问地址')),
                ('index', models.ImageField(default=100, upload_to='', verbose_name='轮播图顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='轮播图添加时间')),
            ],
            options={
                'verbose_name': '网站轮播图表',
                'verbose_name_plural': '网站轮播图表',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10, verbose_name='邮箱验证类型')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '用户邮箱验证码表',
                'verbose_name_plural': '用户邮箱验证码表',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='', max_length=128, verbose_name='密码')),
                ('last_login', models.DateTimeField(null=True, verbose_name='登录日期')),
                ('is_superuser', models.BooleanField(max_length=1, verbose_name='用户身份')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('first_name', models.CharField(max_length=30, verbose_name='拓展1')),
                ('last_name', models.CharField(max_length=30, verbose_name='拓展2')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('is_staff', models.BooleanField(max_length=1, verbose_name='是否是员工')),
                ('is_active', models.BooleanField(max_length=1, verbose_name='是否激活')),
                ('date_joined', models.DateTimeField(null=True, verbose_name='注册日期')),
                ('nick_name', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('birday', models.DateField(null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=3, verbose_name='性别')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地区')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机')),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
            },
        ),
    ]
